export enum EntityNames {
    User="user",
    Otp="otp",
    Profile="profile",
    Category="category",
    Blog="blog",
    BlogCategory="blog_category",
    BlogLikes="blog_likes",
    BlogBookmarks="blog_bookmarks",
    BlogComments="blog_comments",
    Course="course",
    CourseCategory="course_category",
    CourseStudent="course_student",
    Chapter="chapter",
    Sesstion="sesstion",
    CourseComment="course_comment",
    Discount="discount",
    Basket="basket"
}